#!/usr/bin/env python3
"""
XenCDN v8.2 - Edge Configuration Tasks
BGP, GRE tunnel, and edge node management tasks
"""

import os
import json
import logging
from celery import shared_task
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_bgp_config(config_data):
    """Generate Bird2/FRR BGP configuration"""
    
    if config_data['peering_method'] == 'IXP':
        # Bird2 configuration for IXP peering
        bird_config = f"""
# Bird2 BGP Configuration for {config_data.get('isp_name', 'ISP')}
# Generated by XenCDN v8.2

router id {config_data['anycast_ip']};

# Define our ASN
local as {config_data['isp_asn']};

# BGP protocol for IXP peering
protocol bgp xencdn_ixp {{
    description "XenCDN IXP Peering";
    local as {config_data['isp_asn']};
    neighbor {config_data['peer_ip']} as {config_data['local_asn']};
    
    # Multihop not needed for IXP
    multihop off;
    
    # BGP session settings
    connect retry time 30;
    hold time 90;
    keepalive time 30;
    
    # Route import/export
    import filter {{
        # Accept default route and more specifics
        if net ~ [ 0.0.0.0/0, 203.0.113.0/8+ ] then accept;
        reject;
    }};
    
    export filter {{
        # Announce our anycast prefix
        if net = {config_data['anycast_ip']}/32 then accept;
        reject;
    }};
    
    # Security settings
    password "{config_data.get('bgp_password', 'xencdn-secure-2024')}";
    
    # Enable graceful restart
    graceful restart on;
}}

# Static route for our anycast IP
protocol static {{
    route {config_data['anycast_ip']}/32 via "lo";
}}

# Device protocol
protocol device {{
    scan time 10;
}}

# Kernel protocol
protocol kernel {{
    ipv4 {{
        import none;
        export all;
    }};
}}
"""
    
    elif config_data['peering_method'] == 'Direct':
        # Direct peering configuration
        bird_config = f"""
# Bird2 BGP Configuration for Direct Peering
# Generated by XenCDN v8.2

router id {config_data['anycast_ip']};
local as {config_data['isp_asn']};

# BGP protocol for direct peering
protocol bgp xencdn_direct {{
    description "XenCDN Direct Peering";
    local as {config_data['isp_asn']};
    neighbor {config_data['peer_ip']} as {config_data['local_asn']};
    
    # Direct connection settings
    multihop off;
    source address {config_data.get('local_ip', config_data['anycast_ip'])};
    
    # BGP session settings
    connect retry time 60;
    hold time 180;
    keepalive time 60;
    
    # Route policies
    import filter {{
        if net ~ [ 0.0.0.0/0, 203.0.113.0/8+ ] then accept;
        reject;
    }};
    
    export filter {{
        if net = {config_data['anycast_ip']}/32 then accept;
        reject;
    }};
    
    # Authentication
    password "{config_data.get('bgp_password', 'xencdn-direct-2024')}";
    
    graceful restart on;
}}

protocol static {{
    route {config_data['anycast_ip']}/32 via "lo";
}}

protocol device {{
    scan time 10;
}}

protocol kernel {{
    ipv4 {{
        import none;
        export all;
    }};
}}
"""
    
    elif config_data['peering_method'] == 'GRE':
        # GRE tunnel configuration
        bird_config = f"""
# Bird2 BGP Configuration for GRE Tunnel
# Generated by XenCDN v8.2

router id {config_data['anycast_ip']};
local as {config_data['isp_asn']};

# BGP protocol over GRE tunnel
protocol bgp xencdn_gre {{
    description "XenCDN GRE Tunnel Peering";
    local as {config_data['isp_asn']};
    neighbor {config_data['peer_ip']} as {config_data['local_asn']};
    
    # Tunnel settings
    multihop 2;
    source address {config_data.get('tunnel_local_ip', '10.0.0.1')};
    
    # BGP session settings
    connect retry time 120;
    hold time 240;
    keepalive time 80;
    
    # Route policies
    import filter {{
        if net ~ [ 0.0.0.0/0, 203.0.113.0/8+ ] then accept;
        reject;
    }};
    
    export filter {{
        if net = {config_data['anycast_ip']}/32 then accept;
        reject;
    }};
    
    # Authentication
    password "{config_data.get('bgp_password', 'xencdn-gre-2024')}";
    
    graceful restart on;
}}

protocol static {{
    route {config_data['anycast_ip']}/32 via "lo";
}}

protocol device {{
    scan time 15;
}}

protocol kernel {{
    ipv4 {{
        import none;
        export all;
    }};
}}
"""

    else:
        # Default configuration
        bird_config = f"""
# Bird2 BGP Configuration
# Generated by XenCDN v8.2

router id {config_data['anycast_ip']};
local as {config_data['isp_asn']};

# BGP protocol
protocol bgp xencdn {{
    description "XenCDN Peering";
    local as {config_data['isp_asn']};
    neighbor {config_data['peer_ip']} as {config_data['local_asn']};
    
    import all;
    export filter {{
        if net = {config_data['anycast_ip']}/32 then accept;
        reject;
    }};
}}

protocol static {{
    route {config_data['anycast_ip']}/32 via "lo";
}}

protocol device {{}}
protocol kernel {{
    ipv4 {{
        import none;
        export all;
    }};
}}
"""
    
    return bird_config.strip()

def generate_gre_tunnel_script(script_data):
    """Generate GRE tunnel setup script"""
    
    script = f"""#!/bin/bash
# GRE Tunnel Setup Script for XenCDN v8.2
# Generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC

set -e

# Configuration
LOCAL_IP="{script_data['local_ip']}"
REMOTE_IP="{script_data['remote_ip']}"
TUNNEL_LOCAL="{script_data.get('tunnel_local_ip', '10.0.0.1')}"
TUNNEL_REMOTE="{script_data.get('tunnel_remote_ip', '10.0.0.2')}"
TUNNEL_NAME="xencdn-gre"
ANYCAST_IP="{script_data['anycast_ip']}"

echo "Setting up GRE tunnel for XenCDN..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Install required packages
echo "Installing required packages..."
apt-get update
apt-get install -y iproute2 bird2

# Create GRE tunnel
echo "Creating GRE tunnel: $TUNNEL_NAME"
ip tunnel add $TUNNEL_NAME mode gre remote $REMOTE_IP local $LOCAL_IP ttl 255
ip link set $TUNNEL_NAME up
ip addr add $TUNNEL_LOCAL/30 dev $TUNNEL_NAME

# Configure loopback for anycast IP
echo "Configuring anycast IP on loopback..."
ip addr add $ANYCAST_IP/32 dev lo

# Configure routing
echo "Setting up routing..."
ip route add $TUNNEL_REMOTE/32 dev $TUNNEL_NAME

# Enable IP forwarding
echo "Enabling IP forwarding..."
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
sysctl -p

# Configure iptables (basic)
echo "Configuring iptables..."
iptables -A INPUT -p gre -j ACCEPT
iptables -A OUTPUT -p gre -j ACCEPT
iptables -A INPUT -i $TUNNEL_NAME -j ACCEPT
iptables -A OUTPUT -o $TUNNEL_NAME -j ACCEPT

# Save iptables rules (Ubuntu/Debian)
if command -v iptables-save >/dev/null 2>&1; then
    iptables-save > /etc/iptables/rules.v4
fi

# Test connectivity
echo "Testing tunnel connectivity..."
if ping -c 3 $TUNNEL_REMOTE; then
    echo "✅ GRE tunnel is working!"
else
    echo "❌ GRE tunnel test failed"
    exit 1
fi

echo "🎉 GRE tunnel setup completed!"
"""
    
    return script

@shared_task(bind=True, max_retries=3)
def deploy_edge_node_config(self, edge_node_id, config_type='nginx'):
    """Deploy configuration to edge node"""
    try:
        from models import db, EdgeNode
        
        edge_node = EdgeNode.query.get(edge_node_id)
        if not edge_node:
            return {'error': 'Edge node not found'}
        
        # In production, this would use Ansible to deploy configs
        logger.info(f"Deploying {config_type} config to edge node {edge_node.hostname}")
        
        # Mock deployment
        import time
        time.sleep(5)  # Simulate deployment time
        
        # Update edge node status
        edge_node.status = 'active'
        edge_node.updated_at = datetime.utcnow()
        db.session.commit()
        
        return {
            'success': True,
            'edge_node': edge_node.hostname,
            'config_type': config_type,
            'deployed_at': datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Failed to deploy config to edge node {edge_node_id}: {str(e)}")
        
        if self.request.retries < self.max_retries:
            raise self.retry(countdown=60 * (self.request.retries + 1), exc=e)
        
        return {'error': str(e)}

@shared_task(bind=True, max_retries=3) 
def configure_bgp_announcement(self, edge_node_id, anycast_ip):
    """Configure BGP announcement on edge node"""
    try:
        from models import db, EdgeNode
        
        edge_node = EdgeNode.query.get(edge_node_id)
        if not edge_node:
            return {'error': 'Edge node not found'}
        
        logger.info(f"Configuring BGP announcement for {anycast_ip} on {edge_node.hostname}")
        
        # Generate BGP config
        config_data = {
            'isp_asn': os.getenv('BGP_ASN', '65000'),
            'anycast_ip': anycast_ip,
            'peer_ip': edge_node.ip_address,
            'local_asn': os.getenv('BGP_ASN', '65000'),
            'peering_method': 'Direct'
        }
        
        bgp_config = generate_bgp_config(config_data)
        
        # In production, deploy via Ansible
        logger.info(f"BGP config generated for {edge_node.hostname}")
        
        return {
            'success': True,
            'edge_node': edge_node.hostname,
            'anycast_ip': anycast_ip,
            'bgp_config': bgp_config
        }
        
    except Exception as e:
        logger.error(f"Failed to configure BGP on edge node {edge_node_id}: {str(e)}")
        
        if self.request.retries < self.max_retries:
            raise self.retry(countdown=60 * (self.request.retries + 1), exc=e)
        
        return {'error': str(e)}
            'return_code': result.returncode
        }
        
    except subprocess.TimeoutExpired:
        logger.error(f"Ansible playbook {playbook_name} timed out")
        return {
            'success': False,
            'error': 'Playbook execution timed out',
            'return_code': -1
        }
    except Exception as e:
        logger.error(f"Error running Ansible playbook {playbook_name}: {str(e)}")
        return {
            'success': False,
            'error': str(e),
            'return_code': -1
        }

def update_ansible_inventory():
    """Update Ansible inventory with current edge nodes"""
    try:
        edge_nodes = EdgeNode.query.filter_by(status='active').all()
        
        inventory_content = """[edge_nodes]
"""
        
        for node in edge_nodes:
            inventory_content += f"{node.hostname} ansible_host={node.ip_address} ansible_user=root region={node.region}\n"
        
        # Write inventory file
        with open(ANSIBLE_INVENTORY, 'w') as f:
            f.write(inventory_content)
        
        logger.info(f"Ansible inventory updated with {len(edge_nodes)} edge nodes")
        return True
        
    except Exception as e:
        logger.error(f"Error updating Ansible inventory: {str(e)}")
        return False

@shared_task(bind=True, max_retries=3)
def deploy_domain_config(self, domain_id):
    """Deploy domain configuration to all edge nodes"""
    try:
        logger.info(f"Deploying domain configuration for domain ID: {domain_id}")
        
        # Get domain
        domain = Domain.query.get(domain_id)
        if not domain:
            logger.error(f"Domain not found: {domain_id}")
            return {'error': 'Domain not found'}
        
        # Update Ansible inventory
        if not update_ansible_inventory():
            raise Exception("Failed to update Ansible inventory")
        
        # Prepare extra variables for Ansible
        extra_vars = f"""{{
            "domain_name": "{domain.domain_name}",
            "origin_server": "{domain.origin_server}",
            "cache_ttl": {domain.cache_ttl},
            "cdn_enabled": {"true" if domain.cdn_enabled else "false"},
            "ssl_enabled": {"true" if domain.ssl_enabled else "false"}
        }}"""
        
        # Run deployment playbook
        result = run_ansible_playbook('deploy-edge.yml', extra_vars)
        
        if result['success']:
            logger.info(f"Domain configuration deployed successfully: {domain.domain_name}")
            return {
                'success': True,
                'domain': domain.domain_name,
                'stdout': result['stdout']
            }
        else:
            logger.error(f"Domain configuration deployment failed: {result.get('stderr', 'Unknown error')}")
            raise Exception(f"Deployment failed: {result.get('stderr', 'Unknown error')}")
        
    except Exception as e:
        logger.error(f"Deploy domain config error for domain {domain_id}: {str(e)}")
        
        if self.request.retries < self.max_retries:
            logger.info(f"Retrying domain config deployment for domain {domain_id}")
            raise self.retry(countdown=60 * (self.request.retries + 1))
        
        return {'error': str(e)}

@shared_task(bind=True, max_retries=3)
def deploy_edge_node(self, edge_node_id):
    """Deploy and configure new edge node"""
    try:
        logger.info(f"Deploying edge node ID: {edge_node_id}")
        
        # Get edge node
        edge_node = EdgeNode.query.get(edge_node_id)
        if not edge_node:
            logger.error(f"Edge node not found: {edge_node_id}")
            return {'error': 'Edge node not found'}
        
        # Update edge node status
        edge_node.status = 'deploying'
        db.session.commit()
        
        # Create temporary inventory for this node
        temp_inventory_content = f"""[new_edge_nodes]
{edge_node.hostname} ansible_host={edge_node.ip_address} ansible_user=root region={edge_node.region}
"""
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.ini', delete=False) as temp_inventory:
            temp_inventory.write(temp_inventory_content)
            temp_inventory_path = temp_inventory.name
        
        try:
            # Prepare extra variables
            extra_vars = f"""{{
                "edge_node_name": "{edge_node.name}",
                "edge_node_hostname": "{edge_node.hostname}",
                "edge_node_region": "{edge_node.region}",
                "max_clients": {edge_node.max_clients}
            }}"""
            
            # Run edge deployment playbook
            cmd = [
                'ansible-playbook',
                f'{ANSIBLE_PATH}/playbooks/deploy-edge.yml',
                '-i', temp_inventory_path,
                '--config-file', ANSIBLE_CONFIG,
                '--extra-vars', extra_vars,
                '--limit', edge_node.hostname,
                '-v'
            ]
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=1200,  # 20 minutes timeout for initial deployment
                cwd=ANSIBLE_PATH
            )
            
            if result.returncode == 0:
                # Update edge node status
                edge_node.status = 'active'
                edge_node.last_seen = datetime.utcnow()
                edge_node.updated_at = datetime.utcnow()
                db.session.commit()
                
                # Update main inventory
                update_ansible_inventory()
                
                logger.info(f"Edge node deployed successfully: {edge_node.hostname}")
                
                return {
                    'success': True,
                    'edge_node': edge_node.hostname,
                    'stdout': result.stdout
                }
            else:
                # Update edge node status to error
                edge_node.status = 'error'
                edge_node.updated_at = datetime.utcnow()
                db.session.commit()
                
                logger.error(f"Edge node deployment failed: {result.stderr}")
                raise Exception(f"Deployment failed: {result.stderr}")
                
        finally:
            # Clean up temporary inventory file
            os.unlink(temp_inventory_path)
        
    except Exception as e:
        logger.error(f"Deploy edge node error for node {edge_node_id}: {str(e)}")
        
        # Update edge node status to error
        try:
            edge_node = EdgeNode.query.get(edge_node_id)
            if edge_node:
                edge_node.status = 'error'
                edge_node.updated_at = datetime.utcnow()
                db.session.commit()
        except:
            pass
        
        if self.request.retries < self.max_retries:
            logger.info(f"Retrying edge node deployment for node {edge_node_id}")
            raise self.retry(countdown=120 * (self.request.retries + 1))
        
        return {'error': str(e)}

@shared_task(bind=True, max_retries=3)
def update_origin_server(self, domain_id, new_origin):
    """Update origin server configuration on all edge nodes"""
    try:
        logger.info(f"Updating origin server for domain ID: {domain_id}")
        
        # Get domain
        domain = Domain.query.get(domain_id)
        if not domain:
            logger.error(f"Domain not found: {domain_id}")
            return {'error': 'Domain not found'}
        
        # Update Ansible inventory
        if not update_ansible_inventory():
            raise Exception("Failed to update Ansible inventory")
        
        # Prepare extra variables
        extra_vars = f"""{{
            "domain_name": "{domain.domain_name}",
            "old_origin": "{domain.origin_server}",
            "new_origin": "{new_origin}"
        }}"""
        
        # Run origin update playbook
        result = run_ansible_playbook('update-origin.yml', extra_vars)
        
        if result['success']:
            logger.info(f"Origin server updated successfully: {domain.domain_name}")
            return {
                'success': True,
                'domain': domain.domain_name,
                'new_origin': new_origin,
                'stdout': result['stdout']
            }
        else:
            logger.error(f"Origin server update failed: {result.get('stderr', 'Unknown error')}")
            raise Exception(f"Origin update failed: {result.get('stderr', 'Unknown error')}")
        
    except Exception as e:
        logger.error(f"Update origin server error for domain {domain_id}: {str(e)}")
        
        if self.request.retries < self.max_retries:
            logger.info(f"Retrying origin server update for domain {domain_id}")
            raise self.retry(countdown=60 * (self.request.retries + 1))
        
        return {'error': str(e)}

@shared_task
def update_edge_statistics():
    """Update edge node statistics and metrics"""
    try:
        logger.info("Updating edge node statistics")
        
        # Get all active edge nodes
        edge_nodes = EdgeNode.query.filter_by(status='active').all()
        
        for edge_node in edge_nodes:
            try:
                # Check if node is still responsive
                last_seen_threshold = datetime.utcnow() - timedelta(minutes=10)
                
                if edge_node.last_seen and edge_node.last_seen < last_seen_threshold:
                    # Mark as maintenance if not seen for 10 minutes
                    edge_node.status = 'maintenance'
                    logger.warning(f"Edge node marked as maintenance: {edge_node.hostname}")
                
                # Update load score based on client count
                if edge_node.client_count and edge_node.max_clients:
                    edge_node.load_score = edge_node.client_count / edge_node.max_clients
                else:
                    edge_node.load_score = 0.0
                
                edge_node.updated_at = datetime.utcnow()
                
            except Exception as e:
                logger.error(f"Error updating statistics for edge node {edge_node.hostname}: {str(e)}")
        
        db.session.commit()
        
        logger.info(f"Edge node statistics updated for {len(edge_nodes)} nodes")
        
        return {
            'success': True,
            'nodes_updated': len(edge_nodes)
        }
        
    except Exception as e:
        logger.error(f"Update edge statistics error: {str(e)}")
        return {'error': str(e)}

@shared_task
def collect_cache_statistics():
    """Collect cache statistics from all edge nodes"""
    try:
        logger.info("Collecting cache statistics from edge nodes")
        
        # Update Ansible inventory
        if not update_ansible_inventory():
            raise Exception("Failed to update Ansible inventory")
        
        # Run statistics collection playbook
        result = run_ansible_playbook('collect-stats.yml')
        
        if result['success']:
            logger.info("Cache statistics collected successfully")
            
            # Parse and store statistics (simplified)
            # In a real implementation, you would parse the Ansible output
            # and update the CacheStats table with actual data
            
            return {
                'success': True,
                'stdout': result['stdout']
            }
        else:
            logger.error(f"Cache statistics collection failed: {result.get('stderr', 'Unknown error')}")
            return {
                'success': False,
                'error': result.get('stderr', 'Unknown error')
            }
        
    except Exception as e:
        logger.error(f"Collect cache statistics error: {str(e)}")
        return {'error': str(e)}

@shared_task
def maintenance_mode_toggle(edge_node_id, enable_maintenance=True):
    """Toggle maintenance mode for edge node"""
    try:
        logger.info(f"Toggling maintenance mode for edge node ID: {edge_node_id}")
        
        # Get edge node
        edge_node = EdgeNode.query.get(edge_node_id)
        if not edge_node:
            logger.error(f"Edge node not found: {edge_node_id}")
            return {'error': 'Edge node not found'}
        
        # Update status
        if enable_maintenance:
            edge_node.status = 'maintenance'
        else:
            edge_node.status = 'active'
        
        edge_node.updated_at = datetime.utcnow()
        db.session.commit()
        
        # Update Ansible inventory
        update_ansible_inventory()
        
        mode = "enabled" if enable_maintenance else "disabled"
        logger.info(f"Maintenance mode {mode} for edge node: {edge_node.hostname}")
        
        return {
            'success': True,
            'edge_node': edge_node.hostname,
            'maintenance_mode': enable_maintenance
        }
        
    except Exception as e:
        logger.error(f"Maintenance mode toggle error for edge node {edge_node_id}: {str(e)}")
        return {'error': str(e)}

@shared_task
def bulk_deploy_domains():
    """Deploy all active domains to all edge nodes"""
    try:
        logger.info("Starting bulk domain deployment")
        
        # Get all active domains
        domains = Domain.query.filter_by(status='active', cdn_enabled=True).all()
        
        if not domains:
            logger.info("No active domains found for deployment")
            return {'success': True, 'domains_deployed': 0}
        
        # Update Ansible inventory
        if not update_ansible_inventory():
            raise Exception("Failed to update Ansible inventory")
        
        deployment_results = []
        
        for domain in domains:
            try:
                # Deploy domain configuration
                task_result = deploy_domain_config.delay(domain.id)
                deployment_results.append({
                    'domain_id': domain.id,
                    'domain_name': domain.domain_name,
                    'task_id': task_result.id
                })
            except Exception as e:
                logger.error(f"Error starting deployment for domain {domain.domain_name}: {str(e)}")
                deployment_results.append({
                    'domain_id': domain.id,
                    'domain_name': domain.domain_name,
                    'error': str(e)
                })
        
        logger.info(f"Bulk domain deployment initiated for {len(domains)} domains")
        
        return {
            'success': True,
            'total_domains': len(domains),
            'deployment_results': deployment_results
        }
        
    except Exception as e:
        logger.error(f"Bulk deploy domains error: {str(e)}")
        return {'error': str(e)}